name: CI

on:
  push:
    # Run on the main branch
    branches:
      - main
    # Releases are tags named 'v<version>', and must have the "major.minor.micro", for example: "0.1.0".
    # Release candidates are tagged as `v<version>-rc<num>`, for example: "0.1.0-rc1".
    tags:
      - "v*"
  # Also on PRs, just be careful not to publish anything
  pull_request:


jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        if: github.ref == 'refs/heads/main'
        run: |
          pip3 install adafruit-nrfutil
          cargo install cargo-binutils

      - name: Build
        run: |
          for p in firmware/boot firmware/app pinetime-flash watchful-ui; do
            pushd $p;
            cargo build --release;
            popd;
          done

      - name: Build release artifacts
        if: github.ref == 'refs/heads/main'
        run: |
          cd firmware/app
          cargo objcopy --release -- -O binary watchful.bin
          cargo objcopy --release -- -O ihex watchful.hex
          adafruit-nrfutil dfu genpkg --application watchful.hex watchful-dfu.zip

      - name: Upload binary
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: watchful.bin
          path: firmware/app/watchful.bin

      - name: Upload HEX
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: watchful.hex
          path: firmware/app/watchful.hex

      - name: Upload DFU bundle
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: watchful.hex
          path: firmware/app/watchful-dfu.zip
